
import React, { useState } from 'react';
import { GeneratedImage, ImageQuality, ImageMetadata } from '../types';
import { validateMetadata } from '../services/validatorService';
import { Button } from './Button';
import { 
  CheckCircle, 
  XCircle, 
  AlertTriangle, 
  Download, 
  FileText, 
  Globe, 
  ShieldAlert, 
  Info
} from 'lucide-react';

interface ContributorGuideProps {
  image: GeneratedImage;
  metadata?: ImageMetadata;
  onClose: () => void;
}

type Platform = 'Adobe Stock' | 'Shutterstock' | 'iStock/Getty';

const PLATFORMS: Record<Platform, {
  minMP: number;
  formats: string[];
  titleLen: [number, number];
  keywords: [number, number];
  reviewTime: string;
  prohibited: string[];
  color: string;
}> = {
  'Adobe Stock': {
    minMP: 4,
    formats: ['JPEG'],
    titleLen: [5, 70], // strict display limit
    keywords: [5, 50],
    reviewTime: '3-5 Days',
    prohibited: ['Editorial Use Only (for AI)', 'Famous People', 'Logos'],
    color: 'border-red-500 text-red-500'
  },
  'Shutterstock': {
    minMP: 4,
    formats: ['JPEG', 'EPS'],
    titleLen: [20, 200],
    keywords: [7, 50],
    reviewTime: '1-3 Days',
    prohibited: ['Bio-metric data', 'Copyrighted Characters', 'Brand Names'],
    color: 'border-red-600 text-red-600'
  },
  'iStock/Getty': {
    minMP: 3, // roughly
    formats: ['JPEG'],
    titleLen: [5, 80],
    keywords: [5, 50],
    reviewTime: '1-2 Weeks',
    prohibited: ['Specific Buildings (Prop Release)', 'Visible Tattoos (Model Release)'],
    color: 'border-blue-500 text-blue-500'
  }
};

export const ContributorGuide: React.FC<ContributorGuideProps> = ({ image, metadata, onClose }) => {
  const [activePlatform, setActivePlatform] = useState<Platform>('Adobe Stock');
  const platform = PLATFORMS[activePlatform];

  // Resolution Check
  const is1K = image.params.quality === ImageQuality.ONE_K; // ~1MP
  const is2K = image.params.quality === ImageQuality.TWO_K; // ~4MP
  const is4K = image.params.quality === ImageQuality.FOUR_K; // ~16MP
  
  const currentMP = is1K ? 1 : (is2K ? 4.2 : 16.8);
  const resPass = currentMP >= platform.minMP;

  // Metadata Check
  const validation = metadata ? validateMetadata(metadata) : null;
  const metadataScore = validation?.score || 0;
  const metadataPass = metadataScore > 80;

  // Compliance Checks
  const checklist = [
    {
      label: "Image Resolution",
      pass: resPass,
      msg: resPass 
        ? `Quality ${image.params.quality} (~${currentMP.toFixed(1)} MP) meets minimum ${platform.minMP} MP requirement.`
        : `Quality ${image.params.quality} (~${currentMP.toFixed(1)} MP) is too low. Use 2K or 4K settings.`
    },
    {
      label: "Metadata Quality",
      pass: metadataPass,
      msg: metadataPass 
        ? "Metadata score is healthy." 
        : "Metadata needs improvement (Score < 80). Check the Metadata panel."
    },
    {
      label: "AI Marking",
      pass: metadata?.isAI ?? false,
      msg: (metadata?.isAI ?? false) 
        ? "Correctly marked as AI generated." 
        : "Must explicitly tag as Generative AI."
    },
    {
      label: "Format",
      pass: true,
      msg: `Platform requires ${platform.formats.join(' or ')}. Ensure you download as PNG and convert to High-Quality JPEG.`
    }
  ];

  const generateGuideMarkdown = () => {
    if (!metadata) return "No metadata available.";

    return `# ${activePlatform} Submission Guide
Generated by GenStudio Pro

## Image Information
- **Title:** ${metadata.title}
- **Description:** ${metadata.description}
- **Keywords:** ${metadata.keywords.join(', ')}
- **Category:** ${metadata.category}
- **Content Type:** ${metadata.contentType}
- **AI Generated:** Yes

## ${activePlatform} Checklist
[${resPass ? 'x' : ' '}] Resolution > ${platform.minMP} MP (Current: ${image.params.quality})
[${metadataPass ? 'x' : ' '}] Metadata Validated
[x] No Logos/Brands (Visual Check Required)

## Step-by-Step Upload
1. **Export:** Convert your downloaded PNG to JPEG (Quality 100, No Subsampling).
2. **Embed:** Use Adobe Bridge, Photoshop, or ExifTool to embed the Title, Description, and Keywords into the IPTC fields.
3. **Upload:** Log in to ${activePlatform} Contributor Portal.
4. **Tagging:**
   - Ensure "Created with Generative AI" checkbox is ticked.
   - If asked for a property release, usually ignore for pure AI *unless* the platform specifically requires a dummy release (Shutterstock/Adobe sometimes require a generic AI property release).
5. **Review:** Double check categories.
6. **Submit:** Submit for review. Expected wait: ${platform.reviewTime}.

## Prohibited Content Reminders
${platform.prohibited.map(p => `- ${p}`).join('\n')}
    `;
  };

  const handleDownloadGuide = () => {
    const text = generateGuideMarkdown();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${activePlatform.replace(' ', '_')}_Guide.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
      <div className="bg-zinc-900 border border-zinc-800 rounded-xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl">
        
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-zinc-800 bg-zinc-900 rounded-t-xl">
          <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <Globe className="text-blue-400" />
              Contributor Guide
            </h2>
            <p className="text-sm text-zinc-400">Platform-specific submission rules and compliance check.</p>
          </div>
          <button onClick={onClose} className="text-zinc-500 hover:text-white transition-colors">
            <XCircle size={24} />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-zinc-800 bg-zinc-950/50 px-6 pt-2 gap-1">
          {(Object.keys(PLATFORMS) as Platform[]).map((p) => (
            <button
              key={p}
              onClick={() => setActivePlatform(p)}
              className={`px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
                activePlatform === p
                  ? `text-white border-blue-500 bg-zinc-800/50 rounded-t-lg`
                  : 'text-zinc-500 border-transparent hover:text-zinc-300 hover:bg-zinc-800/30'
              }`}
            >
              {p}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto p-6 flex flex-col md:flex-row gap-8">
          
          {/* Left: Checklist & Requirements */}
          <div className="flex-1 space-y-6">
            <div>
              <h3 className="text-sm font-semibold text-zinc-200 mb-4 flex items-center gap-2">
                <ShieldAlert className="w-4 h-4 text-yellow-500" />
                Compliance Checklist
              </h3>
              <div className="space-y-3">
                {checklist.map((item, idx) => (
                  <div key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-zinc-800/50 border border-zinc-700/50">
                    {item.pass ? (
                      <CheckCircle className="w-5 h-5 text-green-500 shrink-0" />
                    ) : (
                      <AlertTriangle className="w-5 h-5 text-red-500 shrink-0" />
                    )}
                    <div>
                      <div className="text-sm font-medium text-zinc-200">{item.label}</div>
                      <div className="text-xs text-zinc-500 mt-0.5">{item.msg}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <h3 className="text-sm font-semibold text-zinc-200 mb-3 flex items-center gap-2">
                <Info className="w-4 h-4 text-blue-400" />
                Platform Rules
              </h3>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 bg-zinc-800/30 rounded border border-zinc-800">
                  <span className="text-[10px] uppercase text-zinc-500 block">Review Time</span>
                  <span className="text-sm font-medium text-zinc-300">{platform.reviewTime}</span>
                </div>
                <div className="p-3 bg-zinc-800/30 rounded border border-zinc-800">
                   <span className="text-[10px] uppercase text-zinc-500 block">Min Resolution</span>
                   <span className="text-sm font-medium text-zinc-300">{platform.minMP} Megapixels</span>
                </div>
              </div>
              <div className="mt-3 p-3 bg-red-900/10 rounded border border-red-900/20">
                 <span className="text-[10px] uppercase text-red-400 block mb-1">Prohibited Content</span>
                 <ul className="list-disc pl-4">
                   {platform.prohibited.map((p, i) => (
                     <li key={i} className="text-xs text-red-200/80">{p}</li>
                   ))}
                 </ul>
              </div>
            </div>
          </div>

          {/* Right: Step by Step */}
          <div className="flex-1 bg-zinc-950 rounded-lg border border-zinc-800 p-5 flex flex-col">
             <h3 className="text-sm font-semibold text-zinc-200 mb-4 flex items-center gap-2">
               <FileText className="w-4 h-4 text-purple-400" />
               Submission Steps
             </h3>
             
             <div className="space-y-4 text-sm text-zinc-400 flex-1 overflow-y-auto pr-2 custom-scrollbar">
               <div className="flex gap-3">
                 <span className="flex-none w-6 h-6 rounded-full bg-zinc-800 text-zinc-300 flex items-center justify-center text-xs font-bold border border-zinc-700">1</span>
                 <div>
                   <p className="text-zinc-200 font-medium">Prepare File</p>
                   <p className="text-xs mt-1">
                     Upscale to {platform.minMP}MP+ if needed. Ensure 100% quality JPEG. 
                     {image.params.quality === '1K' && <span className="text-red-400 block mt-1">Warning: Current 1K image is likely too small.</span>}
                   </p>
                 </div>
               </div>

               <div className="flex gap-3">
                 <span className="flex-none w-6 h-6 rounded-full bg-zinc-800 text-zinc-300 flex items-center justify-center text-xs font-bold border border-zinc-700">2</span>
                 <div>
                   <p className="text-zinc-200 font-medium">Embed Metadata</p>
                   <p className="text-xs mt-1">Copy Title, Description, and Keywords from the Metadata panel into your file's IPTC/XMP data using Adobe Bridge or similar tools.</p>
                 </div>
               </div>

               <div className="flex gap-3">
                 <span className="flex-none w-6 h-6 rounded-full bg-zinc-800 text-zinc-300 flex items-center justify-center text-xs font-bold border border-zinc-700">3</span>
                 <div>
                   <p className="text-zinc-200 font-medium">Upload & Tag</p>
                   <p className="text-xs mt-1">Upload to {activePlatform}. <b>Crucial:</b> Mark the "Created using Generative AI Tools" checkbox during submission.</p>
                 </div>
               </div>
               
               <div className="flex gap-3">
                 <span className="flex-none w-6 h-6 rounded-full bg-zinc-800 text-zinc-300 flex items-center justify-center text-xs font-bold border border-zinc-700">4</span>
                 <div>
                   <p className="text-zinc-200 font-medium">Legal</p>
                   <p className="text-xs mt-1">Ensure no logos or identifiable faces are visible unless you have a model release. For AI people, a property release is often required by {activePlatform}.</p>
                 </div>
               </div>
             </div>

             <div className="mt-6 pt-6 border-t border-zinc-800">
                <Button onClick={handleDownloadGuide} variant="primary" className="w-full" icon={<Download className="w-4 h-4"/>}>
                  Download Guide (.md)
                </Button>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};
